services:
  demo:
    build:
      context: ..
      dockerfile: demo/Dockerfile
    ports:
      - "${FRONTEND_PORT_DEMO:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ../frontend/src:/frontend/src
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-change-in-production
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=http://localhost:3001
      - ADMIN_EMAIL=admin@example.com
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ../backend:/app
      - /app/node_modules
      - ../uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-jwt-secret-change-in-production
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db

  db:
    image: alpine:latest
    command: tail -f /dev/null
    volumes:
      - ../backend/prisma:/data

volumes:
  uploads:
